# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e7a38707-13f3-4e07-81ed-e96c590cd86c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e7a38707-13f3-4e07-81ed-e96c590cd86c".device = "/dev/disk/by-uuid/e7a38707-13f3-4e07-81ed-e96c590cd86c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B2A1-40A4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3cc56da5-7bde-446f-9a79-6c630a4252ea"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
