# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5cc05429-bd2c-48a8-a7f7-070847c61757";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5cc05429-bd2c-48a8-a7f7-070847c61757".device = "/dev/disk/by-uuid/5cc05429-bd2c-48a8-a7f7-070847c61757";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/60A7-3CB9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d4c83e4b-d2aa-4b4e-9295-5b7d7620986d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
