# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-087b7649-d546-463e-8d3f-48d5ddf10acc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-087b7649-d546-463e-8d3f-48d5ddf10acc".device = "/dev/disk/by-uuid/087b7649-d546-463e-8d3f-48d5ddf10acc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ACD6-B540";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-1f216f2c-1da0-4388-93f6-94372f3beefb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
