source = ~/.cache/wal/hyprlock-colors.conf

general {
disable_loading_bar = true
hide_cursor = true
grace = 2
}

auth {
    pam:enabled = true
    pam:module = hyprlock

    fingerprint:enabled = true

    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning fingerprint

    fingerprint:retry_delay = 250
}

# Background: blurred screenshot of the current desktop.

background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 6

    noise = 0.02

    contrast = 1.0
    brightness = 1.3

    vibrancy = 0.5
    vibrancy_darkness = 0.0
}

# Large clock.

label {
    monitor =

    text = cmd[update:1000] echo "$(date '+%I:%M')"

    color = $foreground

    font_size = 150
    font_family = CodeNewRoman Nerd Font Propo

    position = 0, 200
    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 2
    shadow_color = $background-solid
}

# Date.

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %B %d')"

    color = $foreground

    font_size = 30
    font_family = CodeNewRoman Nerd Font Propo

    position = 0, 90
    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 2
    shadow_color = $background-solid

}

# Password input.

input-field {
    monitor =

    size = 600, 100

    outline_thickness = 2

    # Accent border matching Waybar hover/active color.
    outer_color = $color9-dim

    # Similar to your translucent Waybar module backgrounds.
    inner_color = $background

    font_color = $color7

    check_color = $color9
    fail_color = $error

    fade_on_empty = false

    rounding = 10

    placeholder_text = <i>Password...</i>
    placeholder_text_color = $foreground-dim

    dots_size = 0.25
    dots_spacing = 0.2

    position = 0, -110
    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 2
    shadow_color = $background-solid

}
